apiVersion: v1
name: alfresco-process-springboot-service
description: A Helm chart for a generic Alfresco Process/Activiti Spring Boot based microservice
version: 2.2.0
keywords:
  - alfresco
  - content
  - content services
  - alfresco content services
  - activiti
  - process
  - alfresco activiti enterprise
  - java
  - spring boot
  - microservice
home: https://www.alfresco.com
maintainers:
  - name: Alfresco
sources:
  - https://github.com/Alfresco/alfresco-process-springboot-service-deployment
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
